// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC961qcgxLScwEBOX6HydJ-gfibI7rKWPw',
    appId: '1:532195209657:web:f097b6e5c88c6ca2950668',
    messagingSenderId: '532195209657',
    projectId: 'sharemedia-820ca',
    authDomain: 'sharemedia-820ca.firebaseapp.com',
    databaseURL: 'https://sharemedia-820ca-default-rtdb.firebaseio.com',
    storageBucket: 'sharemedia-820ca.appspot.com',
    measurementId: 'G-SQ6P601YPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5S7jimpn9Mgprlf7CNdt1HtTQrr4nVM0',
    appId: '1:532195209657:android:08923bde51cb89a3950668',
    messagingSenderId: '532195209657',
    projectId: 'sharemedia-820ca',
    databaseURL: 'https://sharemedia-820ca-default-rtdb.firebaseio.com',
    storageBucket: 'sharemedia-820ca.appspot.com',
  );
}
